[project]
name = "rustcode"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "inquirerpy>=0.3.4",
    "mypy>=1.19.0",
    "pytest>=9.0.2",
    "rich>=14.2.0",
    "tdqm>=0.0.1",
    "typer>=0.20.0",
]
